### ISSUE TITLE
Table:Experiment: animate card margin 

### ISSUE THREAD

**Issue by Lenni009** [Eisvana/Eisvana-Census#99]
Try animating the card margin when expanding the actions.
When actions are collapsed, leave the margin as-is.
When actions are expanded, set margin to 5rem or smth like that.
Use `:has()` for that.

Something like

```css
.census-table article {
transition: margin-block-end var(--pico-transition); 

&:has(details[open]) {
  margin-block-end: 5rem;
}
}
```
